# Generated by Django 4.2.11 on 2024-04-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_delete_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcher',
            name='custom_difficulty',
            field=models.CharField(choices=[('LOWEST', 'Lowest'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('HIGHEST', 'Highest')], default=None, help_text='Set a custom difficulty for the launcher to send less or more partials depending on preference', max_length=15, null=True, verbose_name='Custom Difficulty'),
        ),
    ]
