# Generated by Django 4.2.11 on 2024-05-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_launcher_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvester', models.CharField(max_length=64)),
                ('version', models.CharField(default=None, max_length=20, null=True)),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('launcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.launcher')),
            ],
            options={
                'db_table': 'harvester',
            },
        ),
    ]
