# Generated by Django 4.2.11 on 2024-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_add_harverter'),
    ]

    operations = [
        migrations.AddField(
            model_name='partial',
            name='time_taken',
            field=models.FloatField(default=None, null=True),
        ),
    ]
