# Generated by Django 4.2.11 on 2024-05-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_partial_timetaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='gigahorse_fee',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
