# Generated by Django 4.2.11 on 2024-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_block_gigahorse_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='partial',
            name='plot_size',
            field=models.IntegerFieldField(default=None, null=True),
        ),
    ]
