# Generated by Django 4.2.11 on 2024-06-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_partial_plotsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='partial',
            name='plot_filename',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
