# Generated by Django 4.2.11 on 2024-04-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_launcher_custom_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='picture_url',
            field=models.URLField(max_length=1024, default=None, null=True),
        ),
    ]
