# Generated by Django 4.2.11 on 2025-01-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_partial_plotsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalinfo',
            name='nodes',
            field=models.JSONField(default=dict),
        ),
    ]
