# Generated by Django 4.2.11 on 2025-01-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_globalinfo_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=False)),
                ('message', models.CharField(null=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=50, default='info', null=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'globalmessage',
            },
        ),
    ]
