# Generated by Django 4.2.11 on 2025-11-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_launcher_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmessage',
            name='closing',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
